<a href="https://colab.research.google.com/github/Bayronguerrero/etl-data-pipeline/blob/main/notebooks/etl_seguros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

url raw de clientes:
https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv

url raw de aseguradoras:
https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv


url raw de corrdores:
https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv


url raw de seguro:
https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv

url raw de polizas:
https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv

url raw de sinisetros:
https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv

In [13]:
import pandas as pd
import numpy as np
import re

bloque 1 Cargar datasets en Python

In [19]:

clientes = pd.read_csv("https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv")
clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [20]:
aseguradoras = pd.read_csv("https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv")
aseguradoras.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [21]:
corredores = pd.read_csv("https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv")
corredores.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [22]:
tipos_seguro = pd.read_csv("https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv")
tipos_seguro.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [23]:
polizas = pd.read_csv("https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv")
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [24]:
siniestros = pd.read_csv("https://raw.githubusercontent.com/Bayronguerrero/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv")
siniestros.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

bloque 2 exploracion de datos

In [25]:

clientes.info()
aseguradoras.info()
corredores.info()
tipos_seguro.info()
polizas.info()
siniestros.info()

clientes.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        3030 non-null   int64
 1   nombre            3030 non-null   object
 2   email             3030 non-null   object
 3   genero            2435 non-null   object
 4   fecha_nacimiento  3030 non-null   object
 5   ciudad            3030 non-null   object
 6   segmento          2433 non-null   object
dtypes: int64(1), object(6)
memory usage: 165.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

bloque 3 limpieza de datos

In [26]:


def limpiar_dataframe(df):

    df.columns = df.columns.str.strip().str.lower()

    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip()

    df = df.replace(r'^\s*$', pd.NA, regex=True)

    df = df.drop_duplicates()

    return df

In [29]:
#FUNCIONES GENERALES DE LIMPIEZA
# --------------------------------------------

def normalizar_columnas(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )
    return df


def limpiar_texto_basico(df):
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace(
            ["nan", "None", "NULL", "null", ""],
            pd.NA
        )
    return df


def eliminar_duplicados(df):
    return df.drop_duplicates()


def convertir_fecha_multiple(serie):
    return pd.to_datetime(serie, errors="coerce", dayfirst=False)


def limpiar_numero_mixto(valor):

    if pd.isna(valor):
        return np.nan

    valor = str(valor).strip()

    if valor in ["", "-", "None", "nan", "NULL", "null"]:
        return np.nan

    if "," in valor and "." in valor:

        if valor.rfind(",") > valor.rfind("."):
            valor = valor.replace(".", "")
            valor = valor.replace(",", ".")
        else:
            valor = valor.replace(",", "")

    elif "," in valor:
        valor = valor.replace(",", ".")

    try:
        return float(valor)
    except:
        return np.nan

In [28]:
#NORMALIZACIÓN INICIAL
# --------------------------------------------

dfs = [clientes, aseguradoras, corredores, tipos_seguro, polizas, siniestros]

for i in range(len(dfs)):
    dfs[i] = normalizar_columnas(dfs[i])
    dfs[i] = limpiar_texto_basico(dfs[i])
    dfs[i] = eliminar_duplicados(dfs[i])

clientes, aseguradoras, corredores, tipos_seguro, polizas, siniestros = dfs

In [30]:
#LIMPIEZA DE CLIENTES
# --------------------------------------------

clientes["email"] = clientes["email"].str.lower()

map_genero = {
    "hombre": "Masculino",
    "masculino": "Masculino",
    "m": "Masculino",
    "mujer": "Femenino",
    "femenino": "Femenino",
    "f": "Femenino"
}

clientes["genero"] = clientes["genero"].str.lower().map(map_genero)


map_ciudad = {
    "sanmiguel": "San Miguel",
    "s. miguel": "San Miguel",
    "san miguel": "San Miguel",
    "sta. ana": "Santa Ana",
    "sta ana": "Santa Ana",
    "santa ana": "Santa Ana",
    "ss": "San Salvador",
    "san salvador": "San Salvador"
}

clientes["ciudad"] = clientes["ciudad"].str.lower().replace(map_ciudad)
clientes["ciudad"] = clientes["ciudad"].str.title()

clientes["fecha_nacimiento"] = convertir_fecha_multiple(clientes["fecha_nacimiento"])

clientes["segmento"] = clientes["segmento"].fillna("No especificado")


clientes_validos = clientes[
    clientes["id_cliente"].notna() &
    clientes["nombre"].notna() &
    clientes["email"].notna()
].copy()

clientes_rechazados = clientes[
    clientes["id_cliente"].isna() |
    clientes["nombre"].isna() |
    clientes["email"].isna()
].copy()

In [31]:
## 5. LIMPIEZA DE ASEGURADORAS
# --------------------------------------------

aseguradoras["nombre"] = aseguradoras["nombre"].str.title()
aseguradoras["pais"] = aseguradoras["pais"].str.title()

map_rating = {
    "alto": "Alto",
    "medio": "Medio",
    "bajo": "Bajo"
}

aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].str.lower().map(map_rating)
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No especificado")
aseguradoras["pais"] = aseguradoras["pais"].fillna("No especificado")

In [32]:
# 6. LIMPIEZA DE CORREDORES
# --------------------------------------------

corredores["nombre"] = corredores["nombre"].str.title()
corredores["zona"] = corredores["zona"].str.strip().str.title()

map_nivel = {
    "junior": "Junior",
    "mid": "Mid",
    "senior": "Senior"
}

corredores["nivel"] = corredores["nivel"].str.strip().str.lower().map(map_nivel)
corredores["nivel"] = corredores["nivel"].fillna("No especificado")

corredores["anios_experiencia"] = pd.to_numeric(
    corredores["anios_experiencia"], errors="coerce"
)

In [33]:
# 7. LIMPIEZA DE TIPOS DE SEGURO
# --------------------------------------------

tipos_seguro["tipo"] = tipos_seguro["tipo"].str.title()
tipos_seguro["categoria"] = tipos_seguro["categoria"].str.title()
tipos_seguro["categoria"] = tipos_seguro["categoria"].fillna("No especificado")

tipos_seguro["riesgo_base"] = tipos_seguro["riesgo_base"].apply(limpiar_numero_mixto)

In [34]:
# 8. LIMPIEZA DE POLIZAS
# --------------------------------------------

polizas["fecha_emision"] = convertir_fecha_multiple(polizas["fecha_emision"])

polizas["prima"] = polizas["prima"].apply(limpiar_numero_mixto)
polizas["comision"] = polizas["comision"].apply(limpiar_numero_mixto)
polizas["monto_asegurado"] = polizas["monto_asegurado"].apply(limpiar_numero_mixto)

In [35]:
# 9. LIMPIEZA DE SINIESTROS
# --------------------------------------------

siniestros["fecha_siniestro"] = convertir_fecha_multiple(siniestros["fecha_siniestro"])
siniestros["monto_siniestro"] = siniestros["monto_siniestro"].apply(limpiar_numero_mixto)

map_estado = {
    "abierto": "Abierto",
    "cerrado": "Cerrado",
    "en proceso": "En Proceso",
    "pendiente": "Pendiente"
}

siniestros["estado"] = siniestros["estado"].str.strip().str.lower().map(map_estado)
siniestros["estado"] = siniestros["estado"].fillna("No especificado")

/tmp/ipykernel_311/2372482665.py:26: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(serie, errors="coerce", dayfirst=False)

bloque 4  Transformaciones importantes

In [36]:
#Transformaciones importantes
polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce')

siniestros['fecha_siniestro'] = pd.to_datetime(
    siniestros['fecha_siniestro'], errors='coerce'
)

polizas['prima'] = polizas['prima'].astype(str).str.replace(",", ".")
polizas['comision'] = polizas['comision'].astype(str).str.replace(",", ".")
polizas['monto_asegurado'] = polizas['monto_asegurado'].astype(str).str.replace(",", ".")

polizas['prima'] = pd.to_numeric(polizas['prima'], errors='coerce')
polizas['comision'] = pd.to_numeric(polizas['comision'], errors='coerce')
polizas['monto_asegurado'] = pd.to_numeric(polizas['monto_asegurado'], errors='coerce')

bloque 5 Exportar archivos curated

In [37]:

clientes.to_csv("clientes_curated.csv", index=False)
aseguradoras.to_csv("aseguradoras_curated.csv", index=False)
corredores.to_csv("corredores_curated.csv", index=False)
tipos_seguro.to_csv("tipos_seguro_curated.csv", index=False)
polizas.to_csv("polizas_curated.csv", index=False)
siniestros.to_csv("siniestros_curated.csv", index=False)

bloque 6  Crear tablas en PostgreSQL

In [54]:
from sqlalchemy import text

sql_create_table_clientes = """
CREATE TABLE IF NOT EXISTS clientes(
id_cliente INT PRIMARY KEY,
nombre VARCHAR(150),
email VARCHAR(150),
genero VARCHAR(20),
fecha_nacimiento DATE,
ciudad VARCHAR(100),
segmento VARCHAR(50)
);
"""

sql_create_table_corredores = """
CREATE TABLE IF NOT EXISTS corredores(
id_corredor INT PRIMARY KEY,
nombre VARCHAR(150),
zona VARCHAR(100),
nivel VARCHAR(50),
anios_experiencia INT
);
"""

sql_create_table_tipos_seguro = """
CREATE TABLE IF NOT EXISTS tipos_seguro(
id_tipo_seguro INT PRIMARY KEY,
tipo VARCHAR(100),
categoria VARCHAR(100),
riesgo_base NUMERIC
);
"""

sql_create_table_polizas = """
CREATE TABLE IF NOT EXISTS polizas(
id_poliza INT PRIMARY KEY,
fecha_emision DATE,
id_cliente INT,
id_corredor INT,
id_aseguradora INT,
id_tipo_seguro INT,
prima NUMERIC,
comision NUMERIC,
monto_asegurado NUMERIC
);
"""

sql_create_table_siniestros = """
CREATE TABLE IF NOT EXISTS siniestros(
id_siniestro INT PRIMARY KEY,
id_poliza INT,
fecha_siniestro DATE,
monto_siniestro NUMERIC,
estado VARCHAR(50)
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_table_clientes))
    conn.execute(text(sql_create_table_corredores))
    conn.execute(text(sql_create_table_tipos_seguro))
    conn.execute(text(sql_create_table_polizas))
    conn.execute(text(sql_create_table_siniestros))
    conn.commit()

bloque 7 Conectar con PostgreSQL Cloud

In [39]:

!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url ="postgresql://bayron:0CW7CtY3dMbiCuYpoMl9ZRABrpqcHkWi@dpg-d6qu8d450q8c73bpfcm0-a.oregon-postgres.render.com/etl_seguros_1z27"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 36.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

bloque 8 Cargar datos a la nube

In [55]:
clientes.to_sql('clientes', engine, if_exists='append', index=False)
aseguradoras.to_sql('aseguradoras', engine, if_exists='append', index=False)
corredores.to_sql('corredores', engine, if_exists='append', index=False)
tipos_seguro.to_sql('tipos_seguro', engine, if_exists='append', index=False)
polizas.to_sql('polizas', engine, if_exists='append', index=False)
siniestros.to_sql('siniestros', engine, if_exists='append', index=False)

620

bloque 9 Consultas SQL de análisis

In [59]:
polizas_count = pd.read_sql("SELECT COUNT(*) FROM polizas;", engine)
print(polizas_count)

   count
0  25150

In [60]:
polizas_count

   count
0  25150

In [69]:
sql_query_polizas_by_aseguradora = "SELECT id_aseguradora, COUNT(*) FROM polizas GROUP BY id_aseguradora;"
polizas_by_aseguradora = pd.read_sql(sql_query_polizas_by_aseguradora, engine)
print(polizas_by_aseguradora.head())

   id_aseguradora  count
0               4   1634
1              14   1628
2               3   1730
3               7   1665
4              13   1681

In [67]:
sql_query = "SELECT estado, COUNT(*) FROM siniestros GROUP BY estado;"
siniestros_by_estado = pd.read_sql(sql_query, engine)
print(siniestros_by_estado.head())

            estado  count
0          Cerrado   1322
1  No especificado   1934
2          Abierto   1364

In [71]:
sql_query_sum_monto_siniestro = "SELECT SUM(monto_siniestro) FROM siniestros;"
sum_monto_siniestro_df = pd.read_sql(sql_query_sum_monto_siniestro, engine)
print(sum_monto_siniestro_df)

           sum
0  26607815.21